name: 'Scripting Compiler Action'
description: 'Runs the custom ScriptCompiler as a GitHub Action.'
inputs:
  source-root:
    description: 'The root directory of the source files to compile.'
    required: true
    default: 'src'
  output-file:
    description: 'The path to the output file for the compiled script.'
    required: true
    default: 'output/compiled.lua'
  
runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        npm ci
        npm run build
        node dist/index.js
      shell: bash
      env:
        INPUT_SOURCE-ROOT: ${{ inputs.source-root }}
        INPUT_OUTPUT-FILE: ${{ inputs.output-file }}
    
